"""Configures the application's warning behavior.

This module is responsible for suppressing specific, non-critical warnings
generated by third-party libraries, ensuring a cleaner console output
for the end-user.
"""

import warnings


def setup_warnings() -> None:
    """Suppress common, non-critical warnings from libraries."""
    warnings.filterwarnings("ignore", category=DeprecationWarning)
    warnings.filterwarnings("ignore", category=FutureWarning)
    warnings.filterwarnings("ignore", category=UserWarning)
    warnings.filterwarnings("ignore", category=PendingDeprecationWarning)
